CREATE TABLE IF NOT EXISTS `payment_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NOT NULL,
  `order_no` VARCHAR(32) NOT NULL,
  `trade_order_id` VARCHAR(64) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `channel` VARCHAR(32) NOT NULL DEFAULT 'XUNHUPAY',
  `pay_url` VARCHAR(512),
  `qr_code_url` VARCHAR(512),
  `transaction_id` VARCHAR(64),
  `notify_body` TEXT,
  `app_callback_body` TEXT,
  `app_callback_status` TINYINT NOT NULL DEFAULT 0,
  `app_callback_attempts` INT NOT NULL DEFAULT 0,
  `last_callback_error` VARCHAR(512),
  `paid_time` DATETIME,
  `callback_next_time` DATETIME,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_order_no` (`order_no`),
  UNIQUE KEY `uk_payment_trade_order_id` (`trade_order_id`),
  KEY `idx_payment_callback_retry` (`status`, `app_callback_status`, `callback_next_time`)
);
